### ISSUE TITLE
tests report as passing when they actually fail

### ISSUE THREAD

**Issue by tjwebb** [trailsjs/generator-trails#22]
https://travis-ci.org/trailsjs/generator-trails/jobs/100739885#L1007

**Comment by jaumard** [comment]
It's because of isparta, we use this command `babel-node node_modules/.bin/isparta cover _mocha` and if tests failed coverage is running anyway, so maybe Travis doesn't detect failing tests cause coverage doesn't failed. I disable isparta and travis detect failing tests https://travis-ci.org/trailsjs/generator-trails/builds/102075702 

So for now I disable isparta to have real test unit. But need deep searching to resolve this if we want coverage.
It's on this PR https://github.com/trailsjs/generator-trails/pull/25

**Comment by jaumard** [comment]
Fix on master
