### ISSUE TITLE
Problems with trailpack-sequelize (and maybe other) versions

### ISSUE THREAD

**Issue by rubenmoya** [trailsjs/generator-trails#75]
Hi! I tried to install trailpack using the `v3` branch and I realised that we're using the trails version to install the trailpacks, in the `v3` branch the trails version is set to `next`, but `trailpack-sequelize` doesn't have such version so it leads to an error.

**Comment by jaumard** [comment]
The problem is on the V3 branch, we shouldn't put `next` as it force every trailpacks to have a `next` published version witch is bad. I think I already put a comment on the v3 PR about that. We should put `^3` like the current version is `^2` but you'll have the same problem because none of the trailpacks have v3 version witch is normal. If you want to use the v3 you can't use the generator because the all architecture is not stable. 

Generate a Trails v2 project and modify the package.json to use the v3 version and modify what have change manually
